### ISSUE TITLE
Allow the category attribute to have none or multiple values

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#11]
The platform should handle multiple values for the category attribute. This includes
indexing, visual hints  and form options in the annotator, and back-end support for 
such annotation requests.

- [ ] Change TEI specification if needed.
- [ ] Front-end support for the annotator.
- [ ] Back-end support for the annotator.
- [ ] Front-end support for the TEI stats app.
- [ ] Back-end support for the TEI stats app.

**Comment by michalkozak** [comment]
We will use `ana` atrributtes that will point to the nodes of project specific taxonomy described in #32. 
According to the TEI specification `ana` can cover 1–∞ occurrences of teidata.pointer separated by whitespace.
