### ISSUE TITLE
The annotator fails to create annotations for the name attribute.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#113]
A error occurs when trying to add an annotation referring to the `name` property of an _event_ entity.
This is done using the following request:
```
'{"method":"modify","payload":[ {
    "element_type":"certainty",
    "method":"POST",
    "new_element_id":"event-0/name",
    "parameters":{"categories":"imprecision"],"locus":"value","certainty":"medium","asserted_value":"something","description":""}}]}'
```

The server logs the following error:
```
web_1            | 2020-07-13 14:44:39,280 - ERROR - consumers - Send response to user: 'jancho' with content: '{"status": 500, "message": "Unhandled exception.", "body_content": null}'
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 601, in __get_entity_property_from_db
web_1            |     entity_property = EntityProperty.objects.get(
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
web_1            |     raise self.model.DoesNotExist(
web_1            | apps.api_vis.models.EntityProperty.DoesNotExist: EntityProperty matching query does not exist.
web_1            | 
web_1            | During handling of the above exception, another exception occurred:
web_1            | 
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/consumers.py", line 174, in receive
web_1            |     self.__request_handler.modify_file(operations)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 57, in modify_file
web_1            |     self.__add_certainty(operation)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 472, in __add_certainty
web_1            |     certainty_xml_id = self.__db_handler.add_certainty(certainty_target, parameters)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 80, in add_certainty
web_1            |     target, match = self.__get_certainty_target_and_match(certainty_target, target_type)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 738, in __get_certainty_target_and_match
web_1            |     entity_property = self.__get_entity_property_from_db(target, property_name)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 609, in __get_entity_property_from_db
web_1            |     entity_property = EntityProperty.objects.get(
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
web_1            |     raise self.model.DoesNotExist(
web_1            | apps.api_vis.models.EntityProperty.DoesNotExist: EntityProperty matching query does not exist.


```

**Comment by bug-rancher** [comment]
I added logs to some user operations to better understand the source of the problem. Please:
- pull last changes from `develop` branch
- create new project
- upload fresh files 
- try to cause this bug again

Please attach:
- files you uploaded 
- log files from `colaorative-platform/logs/` directory

**Comment by Janchorizo** [comment]
Hello. I am experiencing this issue again. For some reason I got the following annotation back from the server:
```json
ana: "https://providedh.ehum.psnc.pl/api/projects/1/taxonomy/#imprecision"
assertedValue: "oven"
cert: "medium"
degree: null
deleted: false
desc: null
locus: "value"
match: "./placeName/name"
resp: "#annotator-2"
saved: false
target: "#place-0"
xml:id: "certainty-5"
```

I don't understand why the match is formatted like so. Even though this is not the issue, I would like
to mentioned that I have also encountered the match property formatted like `@cert`, `name/forename`
and `@ref`. I don't understand how I should manage this.

Please clarify it to me. Thanks :+1:

**Comment by bug-rancher** [comment]
This response looks ok.

In the "match" attribute you have the xpath expression to the element in the xml file to which the uncertainty refers. The root element for this expression is the element in the "target" attribute of the same <certainty> element.

Here is description in TEI P5 documentation: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.scoping.html
Examples in documentation: https://tei-c.org/release/doc/tei-p5-doc/en/html/examples-certainty.html
And example in our test files: https://github.com/providedh/collaborative-platform/blob/develop/src/collaborative_platform/apps/close_reading/tests/integration_tests/database_fixture/media/uploaded_files/57319b88c83db459604c7960710f572c674a4b0c271d9112bc4ff49cd690cd094a5e38a115646_ElP9Uro

If you still getting this issue, please help me replicate this issue according to this instruction: https://github.com/providedh/collaborative-platform/issues/113#issuecomment-680771165

**Comment by Janchorizo** [comment]
The documentation states that the value can be an arbitrary xpath expression. It is not feasible to cover that
given the complexity and vast amount of edge cases. 
I understand that there are a limited amount of combinations/xpath expressions that you use. Could you please
share that with me?

Without knowing so I can't provide edit options and correct descriptions for the annotations. I will close the issue
given that there is not a problem but a need of info.

**Comment by bug-rancher** [comment]
All xpaths used in platform are in this file (under `# Entities structure`): https://github.com/providedh/collaborative-platform/blob/develop/src/collaborative_platform/collaborative_platform/settings_template.py

Conversion of the xpath expression from setings file form to form used in `match` attribute is very simple and is described in method `__reformat_xpath()` here: https://github.com/providedh/collaborative-platform/blob/b5ac79c1a122e2f1c55beb957eba10e2fc5beb5b/src/collaborative_platform/apps/close_reading/db_handler.py#L762
