### ISSUE TITLE
Creating a second reference to an entity is not reflected in the operations

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#122]
Branch: develop
Steps to reproduce: having already an entity in the document, select a piece of text and
add an entity (without uncertainty) referring to it. A similar message to this will be sent:
```
{"method":"modify","payload":[
{"element_type":"tag","method":"POST","parameters":{"start_pos":1961,"end_pos":1970}},
{"element_type":"reference","method":"POST","edited_element_id":0,"new_element_id":"event-0"}]}
```

Expected result: two different operations. However only the tag operation is saved:
```
edited_element_id: null
element_type: "tag"
id: 27
method: "POST"
new_element_id: null
old_element_id: null
operation_result: "ab-4"
```
However the name tag correctly refers to the entity that was set to.

**Comment by bug-rancher** [comment]
I tried to replicate this bug, but everything works ok. I suspect problem is somewhere else.

I added logs to some user operations to better understand the source of the problem. Please:
- pull last changes from develop branch
- create new project
- upload fresh files
- try to cause this bug again

Please attach:
- files you uploaded
- log files from colaorative-platform/logs/ directory
