### ISSUE TITLE
Websockets is not sending an updated document after successful operations.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#123]
As the title. Both in the development server and in docker-based local development.

**Comment by bug-rancher** [comment]
I tried to replicate this bug, but everything works ok.

I added logs to some user operations to better understand the source of the problem. Please:
- pull last changes from develop branch
- create new project
- upload fresh files
- try to cause this bug again

Please attach:
- files you uploaded
- log files from colaorative-platform/logs/ directory

**Comment by Janchorizo** [comment]
I work on docker and still have this same issue.

**Comment by bug-rancher** [comment]
So, please do steps I described above and attach uploaded file and log files.

**Comment by Janchorizo** [comment]
Okey, I will report this today. Just wanted to state that I have not been able to receive a response from websockets
since we started with it.
