### ISSUE TITLE
[Annotator] Inoperative discard links are shown

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#138]
If entity is created with parameters entered, these cannot be discarded without discarding the whole entity addition. I don't know if this is desired behaviour, or not? @michalkozak ?

If it's not desired, then the bug is only the above, but otherwise:
Discard buttons/links are shown next to all parameters in entitiy pop-up dialog. The ones assigned to parameters added during entity creation are nonfunctional, while the ones next to parameters added afterwards — as a separate action — are fully functional. Also, click on the nonfunctional link doesn't provide any feedback/error message.

**Comment by Janchorizo** [comment]
There is a difference between the two (added with or after entity creation). The difference is that the first have, as target, the result of the prior operation. With that information it is not
possible to know which operation corresponds to it. Moreover, I found that sometimes the operation is not available:

_These are the two operations returned for the creation of a date with "when" property, (date missing)_
```
{
edited_element_id: null
element_type: "tag"
id: 6
method: "POST"
new_element_id: null
old_element_id: null
operation_result: "ab-3"
}
{
edited_element_id: "ab-3"
element_type: "reference"
id: 7
method: "POST"
new_element_id: null
old_element_id: null
operation_result: "date-5"
}
```

For later properties, the operation already holds all the information needed to discard it:
```
edited_element_id: "date-5"
element_type: "entity_property"
id: 8
method: "POST"
new_element_id: null
old_element_id: null
operation_result: "date-5/name"
```

However, for properties resulting from entity creation I am not quite sure how this could be handled.
