### ISSUE TITLE
[UX] Annotator layout is counter-intuitive in some cases (IMO)

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#139]
I believe, that surname on the left side of the forename, and death date on the left side of the birthdate is not the expected layout, and it causes me to jump around fields, instead of just using tab to go trough fields in given order. Of course others' opinions are welcome — is that just my feeling?

**Comment by Janchorizo** [comment]
This is automatic. I retrieve the available properties from the project's configuration and provide HTML inputs for them. No semantics is applied.

**Comment by virdiignis** [comment]
Can you point me to the endpoint you're using to get these properties?
