### ISSUE TITLE
[Annotator] Selecting entity from list while adding annotation scrolls to top.

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#144]
Every time I add an entity with "This refers to existing entity", when I select entity from list, my browser scrolls to the top of the whole page. Not sure if bug, but it's annoying.

**Comment by Janchorizo** [comment]
Can't reproduce that.

**Comment by virdiignis** [comment]
Try this file, and annotate somewhere in the second half of the text.
[music_history.zip](https://github.com/providedh/collaborative-platform/files/5162358/music_history.zip)

**Comment by Janchorizo** [comment]
Some controls are modeled as `<a href="#"></a>` links, which causes the page to jump to the top.
These will be replaced with buttons styled so that they preserve the style.
