### ISSUE TITLE
Support “machine-generated” uncertainty category

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#15]
Decide o the way to approach and implement the necessary changes needed to
support a new _machine-generated_ category. This would include handling this
new value in the annotator.

A possible approach at this would be relying on the _resp_ attribute to associate
the annotation to a specific algorithm. This would allow to specify further information regarding the algorithm. This approach would probably require the _category_
attribute to be optional.

**Comment by virdiignis** [comment]
After discussion with Michał and Szymon, we propose to approach the task in a following way:
- _ana_ parameter should be set to "https://providedh.ehum.psnc.pl/api/projects/13/taxonomy/#algorythmic", as defined in our default taxonomy;
- _resp_ parameter should be set to id of the artificial user, created in DB for each algorithm used in the system;
- _degree_ parameter should contain number between 0 and 1 representing level of algorithm certainty;
On file upload, (on migrations stage) if _resp_ is set to value absent from the system, new artificial user should be created, with name set to _resp_ value, and new _resp_ value should be set to the artificial user's id.
