### ISSUE TITLE
Annotating entities makes the entity API to stop working for that file

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#158]
**Steps to reproduce:**
1. Create a project
2. Upload a file
3. Open the file in the annotator
4. Annotate and save an entity
5. Access the `/api/vis/projects/<project_id>/files/<file_id>/entities/` endpoint

**Expected behavior:**
The server returns the entities for that specific file, including the last one added.

**Results:**
The server fails to retrieve a response, providing a failure response mentioning:
```
DoesNotExist at /api/vis/projects/1/files/4/entities/
EntityVersion matching query does not exist.
```

The failure page points at lines _349, 350_ in file _api_vis/db_handler.py_:
https://github.com/providedh/collaborative-platform/blob/b82b2dc98db889919e489c56f757bc22b14e5303/src/collaborative_platform/apps/api_vis/db_handler.py#L349-L351

No logs other than the websockets messages can be found from the annotation of these new entities:
```
'{
    "method": "modify",
    "payload": [
        {
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 1291,
                "start_pos": 1280
            }
        },
        {
            "edited_element_id": 0,
            "element_type": "reference",
            "method": "POST",
            "parameters": {
                "entity_type": "place"
            }
        }
    ]
}'
2020-09-16 09:27:00,683 - INFO - Content of file with id: '4' updated with request from user with id: '2' was sent to users with ids: 2
2020-09-16 09:27:03,491 - INFO - Got request from user with id: '2' with content:
'{
    "method": "save",
    "payload": [
        1,
        2
    ]
}'
```

**Comment by bug-rancher** [comment]
I tried to replicate this issue, but everything looks ok. Maybe cause of this issue was fixed during last modifications. Please try to replicate this issue on `develop` branch, with latest changes, latest migrations and fresh database and let me know if this issue still exist.

**Comment by Janchorizo** [comment]
This was fixed during some update, as the disambiguator branch still presents this issue.
