### ISSUE TITLE
Show the degree attribute to the user

### ISSUE THREAD

**Issue by michalkozak** [providedh/collaborative-platform#178]
The certainty element has two attributes carrying information about confidence associated with the object pointed to by this element:
- cert
- degree

The former one (cert) allows assigning coarse-grained values (“high”, “medium”, “low” etc.) and the latter one (degree) allows for more fine-grained numerical values. In the platform we accept for annotation with cert and only this attribute is presented to the user on UI. 
But we also allows for uploading annotated data into the platform, and these data can already have uncertainty annotations with the usage of the degree attribute (probably filled algorithmically because it is likely impossible for humans to ascertain a difference between 0.67 and 0.68 degree of confidence).

Let us also present the values of the degree attribute on the platform. By the way, I have noticed that if there is no assertedValue attribute filled in, the message should be different. Currently it is:

"[I] marked with [medium] [credibility] certainty: that the [value] should be []."

it is not correct. When a user annotate something with uncertainty without providing value, he/she expresses its doubts about this value without stating any other value.

So I suggest to change messages according to these rules:

- cert is given, degree is not given, assertedValue is not given
[I] marked with [cert] [credibility] certainty my doubts about the [value] of [match]    _(of [match] if exist)_

- cert is not given, degree is given, assertedValue is not given
[I] marked with [degree] [credibility] confidence my doubts about the [value] of [match]    _(of [match] if exist)_

- cert is given, degree is given, assertedValue is not given
[I] marked with [cert] ([degree]) [credibility] confidence my doubts about the [value] of [match]    _(of [match] if exist)_

- cert is given, degree is not given, assertedValue is given
[I] marked with [cert] [credibility] certainty that the [value] of [match] be [assertedValue]   _(of [match] if exist)_

- cert is not given, degree is given, assertedValue is given
[I] marked with [degree] [credibility] certainty that the [value] of [match] be [assertedValue]   _(of [match] if exist)_

- cert is given, degree is given, assertedValue is given
[I] marked with [cert] ([degree]) [credibility] certainty that the [value] of [match] be [assertedValue]   _(of [match] if exist)_

**Comment by Janchorizo** [comment]
![image](https://user-images.githubusercontent.com/28607713/101331230-fa7fb500-3873-11eb-89bb-34077ab22bbe.png)

The text description has been changed according to your explanation and the degree value will be shown where possible. I also check for `degree not given, cert not given`, in which case it will be shown:
[I] marked with unspecified [credibility] certainty that the [value] of [match] be [assertedValue] (of [match] if exist)
