### ISSUE TITLE
Move lists of entities to the one dedicated element in TEI

### ISSUE THREAD

**Issue by michalkozak** [providedh/collaborative-platform#179]
The reviewers suggested using the standOff tag as a container for lists of annotated entities. 

Currently we place these lists in the header or the body depending on the user settings
* List existing {entities} in the documents?

So:
- Let's drop these settings abd show the lists always in the annotator.
- Let's create lists in standOff element in TEI
- Let's replace the sample file to the attached (I moved lists from the header to the standOff element).

[tei_sample_document.zip](https://github.com/providedh/collaborative-platform/files/5587872/tei_sample_document.zip)

**Comment by Janchorizo** [comment]
Even if lists are changed in the exported TEI file, why don't we keep the option to show/hide lists in the annotator? I could set the option to list entities `on` by default, but leave it to the user if he/she wants to see a list lf things that may bloat the interface.
I think more options is always a better chioce. What is your decision on that?

**Comment by virdiignis** [comment]
Hi @Janchorizo, we have had internal discussion on that after that issue were created.
Do you find it feasible to show those lists as a drop-down lists (toggled for each entity type), and save information about which ones should be expanded in a cookie? We think that's the simplest way to provide user with a choice, and save preferences per-user, while this info not so important to persist it between sessions.

**Comment by bug-rancher** [comment]
Hi @Janchorizo , I moved lists of entities to `<standOff>` element. I also removed database field which keep information if list is stored in `<body>` element, because now it unnecessary. According to this, information if entity list is stored in `<body>` element was removed from `"preferences"` field in Annotator's and Disambiguator's response.

**Comment by Janchorizo** [comment]
I personally don't understand why the UI has to reflect a TEI decision that would only affect the resulting TEI files.
Nonetheless I changed the project creation app and the annotator accordingly to your decision: for the entity categories
that hold at least one occurrence, a collapsible list will show above the document content.

The changes are in the `tei_format_updates` branch.
