### ISSUE TITLE
Text longer than 1 word in Asserted Value must be wprapped in a separate tag

### ISSUE THREAD

**Issue by michalkozak** [providedh/collaborative-platform#181]
Reviewers pointed out that the transcription given in the assertedValue attribute cannot be longer than one word. The teidata.word type does not accept whitespaces.

So we have to wrap asserted values longer than one word in a separate tag val, and place it under the certainty element. In such cases assertedValue should refer to this element, as in the following example:
```
<classCode schemetype="http://providedh.eu/uncertainty/ns/1.0">
  <certainty xml:id="certainty-1" locus="value" cert="unknown" ana="https://providedh.ehum.psnc.pl/api/projects/1/taxonomy#credibility" target="#name-1" resp="#annotator-4" assertedValue="#val-1"/>
  <val xml:id="val-1">Ambroze Bedel</val>
</classCode>
```

**Comment by bug-rancher** [comment]
Done.
