### ISSUE TITLE
Entities and annotations are not preserved upon upload

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#185]
Branch: `tei_format_updates` (from clean rebuild)
Expected result: Entities and annotations should be preserved
Steps to reproduce: Upload a file with existing entities and annotations
Logs: [logs.zip](https://github.com/providedh/collaborative-platform/files/5614596/logs.zip)
Sample file:  [dep_823036r034_tei_xml.txt](https://github.com/providedh/collaborative-platform/files/5614652/dep_823036r034_tei_xml.txt)

When a file with entities and annotations is uploaded, the `<name .../>` tags for listable entities
but those pre-existing entities are not provided in the websocket messages:

```
{"status":200,"message":"OK","file_version":2,"authors":[],"operations":[],"certainties":[],"entities_lists":{"event":[],"object":[],"org":[],"person":[],"place":[]},"body_content":"[ ... omitted content for brevity ... ]"}
```

**Comment by bug-rancher** [comment]
In file that you provided there is no annotators, no certainties, no entities, just tags in text in `<text>` element, so there is nothing to import, so matching fields in websocket message will be empty.

I see that there are "unsaved" elements in this file. File in this form shouldn't be able to download. Did you download this file directly from platform, or created this file in another way?

**Comment by Janchorizo** [comment]
You can se there are name tags for multiple entities and can check the annotations in the original file https://providedh-test.ehum.psnc.pl/close_reading/project/3/file/4/

I now see that those entities and annotations are missing. That means that the issue migh be on exporting files. Please confirm this happens to you too before closing this issue and opening a new one for file exports.

**Comment by bug-rancher** [comment]
I think the cause of issues you described is mixing branches. You download file from test server (with `develop` branch) and upload them to platform on branch `tei_format_updates`. File format is different on this two branches and this may be a root of problem.

I uploaded example file from here: https://drive.google.com/drive/folders/1PhsbbNRjq8nCBgHLRgq3xyA9PhsLugjw and everything was imported correctly. I added a uncertainty, saved file and download, and everything was in place. I imported this annotated file again, and again everything was imported correctly.

Please try to replicate this issue on `tei_format_updates` branch, with one of sample files from link above and let me know, if this problem still exists.

**Comment by Janchorizo** [comment]
Importing seems to work well with your sample files, so I will now work with the newer format. I will close this issue.
