### ISSUE TITLE
User should define names, icons and colours for the TEI entities.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#35]
Related to #32 

Given that there is already a model for storing the preferences for displaying uncertainty,
we could also provide the ability to define what entities are to be displayed, along with the
colors and icons that should be used.

This could have other implications such as the fact that newer entities would be needed to
be stored and indexed. 

This issue could be associated just with the styling and the indexing be done further in time.

**Comment by ale0xb** [comment]
Overall I think that this is a good idea however I'm not so sure it is a good idea to allow changes to the project settings after indexing has taken place. I discussed this with @bug-rancher and @virdiignis and we'd rather stay on the safe side when it comes down to modify project settings (for now).

**Comment by Janchorizo** [comment]
There are three different topics here: 
- Specifying the number and type of the taxonomy categories and TEI entities.
- Specifying the color and icons used for the taxonomy categories and TEI entities.
- The moment and scope of specifying these settings.

I propose setting all of them upon project creation, and then allow per user tweaking
of the colors and icons for the entities.

**Comment by michalkozak** [comment]
Please read this proposition for this issue before the tomorrow cal:l
https://docs.google.com/document/d/1X4b4EMl1wzyZ_-c6uTJ2EkT_36ODCUJeEp-sOJzECNQ/edit
We can talk about it tomorrow.

**Comment by virdiignis** [comment]
Today I started work on this issue in flexible_taxonomy branch. I will work on that and related issues regaring API endpoints tommorow.

@Janchorizo I need you to change front-end, so the load to the project create endpoint looks like below:
```
{
  "taxonomy": [
    {
      "name":  "ignorance",
      "color": "#FF00FF",
      "icon": "",
      "description": "Category desc."
    },
    {
      "name":  "imprecision",
      "color": "#00FF00",
      "icon": "",
      "description": "Category desc."
    }
  ],
  "entities": [
    {
      "name": "Person",
      "color": "#FFFFFF",
      "icon": "",
      "properties": {
        "attributes": [
          "sex", "age", "role"
        ],
        "sub-elements": [
          "persName", "birth", "death"
        ]
      }
    },
    {
      "name": "Ingredient",
      "color": "#A0A0A0",
      "icon": "",
      "properties": {}
    }
  ]
}
```

Tommorow I will expose default values for that lists in the same format as an endpoint. Also please write here what should I put in icon and color fields for default entities. You're welcome to do changes in the same branch. We'll only merge it after all changes are done.

@michalkozak should I include all available (by the TEI docs) properties, or some subset of those? If latter, also write it down and post here please.

Best regards,

**Comment by Janchorizo** [comment]
This was discussed in the dev channel, and a different approach explained in issue #86 .
Basically, users should not have to deal with TEI properties as the only action to do at
project creation is removing some properties which they can nonetheless omit when annotating.

Therefore properties should be shown (for clarity and informative reasons), but maybe we 
omit them in the project creation message payload.

**Comment by Janchorizo** [comment]
The default values that I show at project creation are the following:
```
"date": 			{"icon": "\\f073", "color": "#868788" },
"event": 			{"icon": "\\f274", "color": "#cecece" },
"location": 		{"icon": "\\f5a0", "color": "#ff6464" },
"geolocation": 		{"icon": "\\f5a0", "color": "#ff6464" },
"occupation": 		{"icon": "\\f0b1", "color": "#3c8745" },
"object": 			{"icon": "\\f466", "color": "#b4d38d" },
"org": 				{"icon": "\\f1ad", "color": "#b4edfc" },
"person": 			{"icon": "\\f007", "color": "#ff7f00" },
"place": 			{"icon": "\\f279", "color": "#204191" },
"placeName": 		{"icon": "\\f279", "color": "#204191" },
"country": 			{"icon": "\\f279", "color": "#204191" },
"time": 			{"icon": "\\f017", "color": "#eab9e4" },
"ingredient": 		{"icon": "\uf787", "color": "#395b50" },
"productionMethod": {"icon": "\\f542", "color": "#291528" },
"utensil": 			{"icon": "\uf6e3", "color": "#96031a" },
```

**Comment by virdiignis** [comment]
>Therefore properties should be shown (for clarity and informative reasons), but maybe we
omit them in the project creation message payload.

It's easier for me if I have them in the payload – I won't have to guess which entities are default and which are added by the user. I will pass those values to front by different endpoint, so you'll just have to send them back to me along with names, icons and colors.

**Comment by michalkozak** [comment]
@virdiignis You shouldn't require in the API the structure of properties:
      "properties": {
        "attributes": [
          "sex", "age", "role"
        ],
        "sub-elements": [
          "persName", "birth", "death"
        ]
      }
This is a matter of logic in backend how to deal with these properties. Some of them attributes of the entity, some are subelements of entity, but very often there are attributes or subelements of subelements. We shouldn't expose for API the structure of properties. Moreover in https://github.com/providedh/collaborative-platform/issues/85 I listed properties for each entity. There is no persName, but forename and surname.

**Comment by virdiignis** [comment]
Ok, so @Janchorizo let's omit properties in the payload. We'll handle this on backend.

**Comment by Janchorizo** [comment]
I am currently working on another task, but will try to make some time this morning and push the changes so that you can test you code with the new project settings ui.

Do I understand it well that both the entities and taxonomy may have an arbitrary (but not zero) 
amount of elements?

**Comment by virdiignis** [comment]
>Do I understand it well that both the entities and taxonomy may have an arbitrary (but not zero)
amount of elements?

That's correct.

**Comment by Janchorizo** [comment]
I have some few last suggestions regarding the payload for project creation.
TEI does have location entities, as it does have geolocation and similar ones. Even if we handle
geolocation as an attribute of the first, there is the possibility of getting a TEI file with geolocation
and country entities.

_I think giving the entities alias would facilitate handling them, as we could handle geolocation,
country, place and location entities as the same one._

Another issue I find with the current proposal is that it does not handle the use case for specifying
which entity lists will be present in the body and which in the header.

**Comment by virdiignis** [comment]
Let's just add "body_list": true/false to payload.

**Comment by virdiignis** [comment]
So, in the end format would be:
```
{
  "taxonomy": [
    {
      "name":  "ignorance",
      "color": "#FF00FF",
      "icon": "",
      "description": "Category desc."
    },
    {
      "name":  "imprecision",
      "color": "#00FF00",
      "icon": "",
      "description": "Category desc."
    }
  ],
  "entities": [
    {
      "name": "Person",
      "color": "#FFFFFF",
      "icon": "",
      "body_list": false,
      }
    },
    {
      "name": "Ingredient",
      "color": "#A0A0A0",
      "icon": "",
      "body_list": true,
    }
  ]
}
```
