### ISSUE TITLE
Better color schemes and glyphs for representing uncertainty in annotator

### ISSUE THREAD

**Issue by ale0xb** [providedh/collaborative-platform#36]
As of now, we are using the scheme of underlining + icons in the annotator to indicate the different kinds/degrees of uncertainty in the text. However, now that we are supporting 5 levels + 2 categories, I've come to think this approach we have been using might be no longer valid. 

I wonder if there's a better combination of colors/glyphs/other techniques to convey the 4 (with their respective 5 levels) + 1 categories in the annotator. For example, we could map categories to different text underline styles as illustrated [here](https://css-tricks.com/styling-underlines-web/). For selecting color maps we could fall back to VSUPs: [explanation](https://medium.com/@uwdata/value-suppressing-uncertainty-palettes-426130122ce9) and [d3 code](https://github.com/uwdata/vsup) (or better, a modification of it).

**Comment by ale0xb** [comment]
I'm thinking that maybe a color map resulting from a combination of light blur + hue + icon might also be worth looking at (and more adequate for text). It would incorporate the notion that texts annotated with uncertainty should be harder to work with (see [this video](https://www.youtube.com/watch?v=E1kSnWvqCw0) by M. Kay)

**Comment by Janchorizo** [comment]
Certainty is not associated to the original text but to the annotation. See the following example
from [the TEI specification](https://tei-c.org/release/doc/tei-p5-doc/es/html/ref-certainty.html):
```
<certainty target="#ESX" locus="name"
 assertedValue="placeName" cert="low">
 <desc>It is unlikely, but possible, that this refers to the place
   rather than the person.</desc>
</certainty>
```
Therefore text should not be less distinguishable based on the certainty. Annotations themselves 
could be made more or less clear based on their certainty.

**Comment by ale0xb** [comment]
I do not agree, I'm referring to the (annotated) text, not the annotations themselves. This is to achieve a bird view of what parts of the original text have been annotated and with what levels/categories of certainty, not the actual annotations made on top (which btw are optional).
