### ISSUE TITLE
Annotation creation fails for files containing non-valid xml:id values.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#46]
https://github.com/providedh/collaborative-platform/blob/1e9f8e88744b3b4a3e27f8d3f5904c9a855bfda2/src/collaborative_platform/apps/close_reading/annotator.py#L584-L592

https://github.com/providedh/collaborative-platform/blob/1e9f8e88744b3b4a3e27f8d3f5904c9a855bfda2/src/collaborative_platform/apps/close_reading/annotator.py#L605-L614

Annotation fails when an xml element is attempted to be created for files which name contains
non valid xml:id values sucha as spaces, semicolons, or others.

This error does not raise an exception that I could see and no response is sent. However, 
consecutive calls will fail as the websocket closes after a Timer Exception is raised.

**Comment by bug-rancher** [comment]
Because `xml:id` must correspond with file name, and in `target` attribute of `certainty` element we can keep multiple values separated by space, I added cleaning names of projects, directories and files, so now they will contain only letters, numbers "-" and "_".
