### ISSUE TITLE
Changes in annotator needed for Ingredient integration

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#56]
We have to make some changes in annotator to incorporate Recipes usecase.

The plan is to use `<listObject>'s` as lists of ingriedients, utensils ets., and in the text of the recipe to annotate only with `<objectName>` tag. Here is the example:
```
<body>
            <div type="ingredient">
                <listObject>
                    <object type="ingredient" xml:id="egg">Egg</object>
                    <object type="ingredient" xml:id="sugar">Sugar</object>
                </listObject>
            </div>
            <div type="utensil">
                <listObject>
                    <object type="utensil" xml:id="spoon">Spoon</object>
                </listObject>
            </div>
            <div type="recipe">
                <p>
                    Take three <objectName ref="egg">eggs</objectName>, mix with three <objectName ref="spoon">spoons</objectName> of <objectName ref="sugar">sugar</objectName>. Bon Appetite!
               </p>
            </div>
 </body>
```

Desired behaviour is that when user annotates new ingredient/utensil/etc., backend will automatically add it to the adequate list, so annotated recipes will always start with proper lists of requisites.
To enable user to annotate in this manner we need changes in annotator.
@Janchorizo, we need changes in annotator frontend. In "Add TEI annotations" tab, when Ingridient, Utensil or ProductionMethod is choosen, we want a list to appear, with avaliable choices of ingridients, utensils or production methods already avaliable in the lists in the file. We can leave parsing those lists into options to you, or we can provide you with the API endpoint returning those. Another option in the list should be "Add new". In case user choses it, the next textField should appear, allowing user to enter name for the new ingriedient/utensil/etc.
Request created by annotator should consist of positions like before, _ref_  set in _attribute_name_ parameter, and _asserted_value_ containing id of _object_ from the list if user chosen an object already avaliable in the file, or the new name inserted by the user otherwise. 
@bug-rancher is already changing annotator backend accordlingly.
Also, we'd like @Janchorizo to render those list in more readable manner, possibly adding some headers, and spliting into separate lines.

**Comment by Janchorizo** [comment]
```
Also, we'd like @Janchorizo to render those list in more readable manner, possibly adding some headers, and spliting into separate lines.
```
I will try to add this via CSS as HTML headers and new lines will mess up the selection.

**Comment by bug-rancher** [comment]
Backend is ready. Changes are in pull request #58.
