### ISSUE TITLE
Creating uncertainty annotations creates ingredient tags.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#64]
If the asserted value for `locus=name` or the tag name is either `ingredient`, `utensil`,
or `productionMethod`, the a tag with such name is created. This is not the desired 
behavior if we were to use lists of objects and the correspondent objectName tag in
the body.

**Comment by bug-rancher** [comment]
Fixed. I added validation for tag names and for now we can add only tags and certainties to tags from white list (`date`, `event`, `location`, `geolocation`, `occupation`, `object`, `org`, `person`, `place`, `placeName`, `country`, `time`). Adding elements to the lists works as before.
