### ISSUE TITLE
Folders can be moved into themselves and then dissappear.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#68]
If dragging a folder on top of itself, the folder is moved into the
own folder, causing the folder to disappear from the file menu.

If trying to open the folder and drag by mistake or started to move 
the folder but ended up in the same place, this problem happens
too.

The api no longer retrieves the file structure including such folder.
https://providedh-test.ehum.psnc.pl/api/files/get_tree/17

**Comment by virdiignis** [comment]
Added validation in backend.
