### ISSUE TITLE
The platform slows down a lot while uploading new files

### ISSUE THREAD

**Issue by ale0xb** [providedh/collaborative-platform#69]
Currently, the process of uploading files is utterly slow. It takes hours to upload a few files.

**Comment by virdiignis** [comment]
@bug-rancher introduced logging of upload proccess to analyze this issue. It seems that proccessing on our side takes less than a second per file. Average time of upload from our computers to test is about 9s, and most of it is just an internet transfer. There is not much we can do about it, as transferring lots of small files is always slow – even on local computer copying millions of small files will take longer than few big files. In addition, Django is single-threaded, so we're unable to upload files in parallel.
