### ISSUE TITLE
Query string do not seem to afect api queries.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#72]
One option for filtering entities is using querystrings. The following attempts do not work.

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?types=person/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?types="person"/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?types=[person]/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?types=["person"]/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?type=person/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?type="person"/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?type=[person]/`

`http://0.0.0.0:8000/api/vis/projects/3/files/43/entities/?type=["person"]/`

Each of them return all the available entities. For this specific case, the file only contains
ingredients and utensils (objects with the type attribute specified).

Am I misinterpreting how it should work?

**Comment by virdiignis** [comment]
I pushed a fix to develop. Also, you cannto add trailling slash to querystring. Moreover arrays in querysting are not constructed with brackets. Correct request would be e.g.:
```
http://localhost:8000/api/vis/projects/1/files/7/entities/?types=ingredient,utensil
```
