### ISSUE TITLE
Only ingredients, utensils and productionMethods present in lists are indexed upon upload

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#73]
When uploading files, only those entities present in lists of ingredients, utensils or production
methods are index. Therefore, other entities are not retrieved in api calls. This does not happen 
with certainty annotations.

**Comment by virdiignis** [comment]
Do you mean that Ingredients, Utensils, and productionMethods out of lists are not indexed, or that entirely different entites like Person, Place etc. are not indexed?

**Comment by Janchorizo** [comment]
Entities outside lists are not indexed upon upload. This is what I experienced.

**Comment by virdiignis** [comment]
Hi,
I cannot reproduce this issue. I've uploaded file with `<object type="ingredient" xml:id="testid1">Water</object>` in recipe (not in the list), and got it properly indexed.
On the screenshot you can see an ingredient marked in the text and found by the autocomplete.
![screenFetch-2020-02-18_09-41-49](https://user-images.githubusercontent.com/10606746/74719273-03938d00-5234-11ea-9135-9a29e85076a0.png)

Also found #83 while checking this.
