### ISSUE TITLE
Other / Unknown option in "Asserted value" submenu

### ISSUE THREAD

**Issue by esenabre** [providedh/collaborative-platform#78]
The control menu of “Asserted value” seems to not contain a default or specific option to indicate an general/top uncertainty value, when users cannot even define this precise level / "tagging" of subcategorization. Maybe a "Other" option (ideally in future versions allowing for defining it as a sort of "folksonomy") could be useful here.

![Screenshot 2020-02-13 11 54 01](https://user-images.githubusercontent.com/865993/74427707-e50a4c00-4e57-11ea-83d7-51960cb033f6.png)

**Comment by Janchorizo** [comment]
The screenshot shows the `tag name` selection control opened. Is this issue referring
to this control or the asserted value control _(when the locus = 'name')_.
