### ISSUE TITLE
Expose default project entities and properties in the API

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#85]
TEI entities and their respective properties should be given to the users as the default
configuration for project creation.

This information is proposed to be exposed through an API.

**Comment by michalkozak** [comment]
I suggest the following list of entities as default configuration:
* Place (forename, surname, occupation, sex, birth, death, age)
* Event
* Org[anization]
* Object
* Place (country, settlement, geo[location])
* Date
* Time
During a project creation user will be able to remove entities from this list.

**Comment by virdiignis** [comment]
`GET /api/projects/default_properties/`
returns the following, in `flexible_taxonomy` branch:
```
{
"person": {
"properties": [
"birth",
"age",
"surname",
"death",
"occupation",
"forename",
"sex"
],
"listable": true
},
"event": {
"properties": [
"text"
],
"listable": true
},
"org": {
"properties": [
"text"
],
"listable": true
},
"object": {
"properties": [
"text"
],
"listable": true
},
"place": {
"properties": [
"country",
"geo",
"settlement"
],
"listable": true
},
"date": {
"properties": [
"when"
],
"listable": false
},
"time": {
"properties": [
"when"
],
"listable": false
}
}
```
