### ISSUE TITLE
API endpoint to expose current entity and taxonomy configuration.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#88]
As the title says, expose the current settings including:
- Entity names and parameters
- Entity color and icon schemes
- Taxonomy (both the categories and their respected colors)

**Comment by virdiignis** [comment]
GET /api/projects/{id}/settings/
returns:
`
{
"entities": [
{
"name": "ent1",
"color": "#000000",
"icon": "XDDD"
}
],
"taxonomy": [
{
"name": "cat1",
"xml_id": "cat1",
"color": "#FFFFFF",
"description": "desc1"
}
]
}
`

At flexible_taxonomy branch.
