### ISSUE TITLE
Problem with annotating an already annotated word

### ISSUE THREAD

**Issue by amelieacdh** [providedh/collaborative-platform#90]
When trying to annotate a word that has already been annotated before, this word doesn't show in the "Target" field, but instead the entire file name.
![image](https://user-images.githubusercontent.com/35766007/75240362-81234400-57c4-11ea-98bd-921effed1f51.png)

**Comment by Janchorizo** [comment]
Not the document name but the entity id (which contains the document name) was showing
up. This behaviu¡our has been changed to show the contents of the referenced element.
