### ISSUE TITLE
Typo in URL to categories of taxonomy in annotations

### ISSUE THREAD

**Issue by michalkozak** [providedh/collaborative-platform#93]
Currently these URLs are in schema:

https://providedh.ehum.psnc.pl/api/projects/3/taxonomy/#imprecision

But the last slash symbol is unnecessary. Is should be generated as:

https://providedh.ehum.psnc.pl/api/projects/3/taxonomy#imprecision

**Comment by virdiignis** [comment]
It is necessary as it's the trailing slash we have configured in Django. Linking to 
https://providedh.ehum.psnc.pl/api/projects/3/taxonomy#imprecision will trigger HTTP 301 redirect to https://providedh.ehum.psnc.pl/api/projects/3/taxonomy#imprecision. Disabling trailing slash can be done for whole project, but that would require changing all URLs in APIs in back-end and front-end.
